"""new models added

Revision ID: c7a82ab91a84
Revises: d7e806040a44
Create Date: 2026-05-18 19:37:02.375493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a82ab91a84'
down_revision: Union[str, Sequence[str], None] = 'd7e806040a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    custom_chatbot_columns = [c['name'] for c in inspector.get_columns('custom_chatbots')]
    users_chatbot_columns = [c['name'] for c in inspector.get_columns('users')]
    # ### commands auto generated by Alembic - please adjust! ###
    if 'organization_id' not in custom_chatbot_columns:
        op.add_column('custom_chatbots', sa.Column('organization_id', sa.Integer(), nullable=True))

    if 'is_public' not in custom_chatbot_columns:
        op.add_column('custom_chatbots', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'custom_chatbots', 'organizations', ['organization_id'], ['id'])

    if '' not in users_chatbot_columns:
        op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'custom_chatbots', type_='foreignkey')
    op.drop_column('custom_chatbots', 'is_public')
    op.drop_column('custom_chatbots', 'organization_id')
    # ### end Alembic commands ###
