"""describe change

Revision ID: d7e806040a44
Revises: f4118d6b5073
Create Date: 2026-05-06 11:49:52.060237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7e806040a44'
down_revision: Union[str, Sequence[str], None] = 'f4118d6b5073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_chatbots', sa.Column('hero_image', sa.String(length=200), nullable=True))
    op.drop_column('custom_chatbots', 'hero_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_chatbots', sa.Column('hero_image_path', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('custom_chatbots', 'hero_image')
    # ### end Alembic commands ###
