"""describe change

Revision ID: f4118d6b5073
Revises: 13b619a2249a
Create Date: 2026-05-06 00:26:32.813317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4118d6b5073'
down_revision: Union[str, Sequence[str], None] = '13b619a2249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_chatbots', sa.Column('retrieval_key', sa.String(length=40), nullable=True))
    op.add_column('custom_chatbots', sa.Column('is_publish', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('custom_chatbots_ibfk_2'), 'custom_chatbots', type_='foreignkey')
    op.drop_constraint(op.f('custom_chatbots_ibfk_1'), 'custom_chatbots', type_='foreignkey')
    op.drop_column('custom_chatbots', 'completed_at')
    op.drop_column('custom_chatbots', 'status')
    op.drop_column('custom_chatbots', 'request_path')
    op.drop_column('custom_chatbots', 'response_content_type')
    op.drop_column('custom_chatbots', 'request_query')
    op.drop_column('custom_chatbots', 'retrie')
    op.drop_column('custom_chatbots', 'error_message')
    op.drop_column('custom_chatbots', 'response_status_code')
    op.drop_column('custom_chatbots', 'tokens_used')
    op.drop_column('custom_chatbots', 'service_id')
    op.drop_column('custom_chatbots', 'request_method')
    op.drop_column('custom_chatbots', 'request_body')
    op.drop_column('custom_chatbots', 'api_key_id')
    op.drop_column('custom_chatbots', 'response_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_chatbots', sa.Column('response_body', sa.BLOB(), nullable=True))
    op.add_column('custom_chatbots', sa.Column('api_key_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('custom_chatbots', sa.Column('request_body', sa.BLOB(), nullable=True))
    op.add_column('custom_chatbots', sa.Column('request_method', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('custom_chatbots', sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('custom_chatbots', sa.Column('tokens_used', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('custom_chatbots', sa.Column('response_status_code', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('custom_chatbots', sa.Column('error_message', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('custom_chatbots', sa.Column('retrie', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('custom_chatbots', sa.Column('request_query', mysql.VARCHAR(length=2000), nullable=True))
    op.add_column('custom_chatbots', sa.Column('response_content_type', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('custom_chatbots', sa.Column('request_path', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('custom_chatbots', sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed'), nullable=False))
    op.add_column('custom_chatbots', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    op.create_foreign_key(op.f('custom_chatbots_ibfk_1'), 'custom_chatbots', 'api_keys', ['api_key_id'], ['id'])
    op.create_foreign_key(op.f('custom_chatbots_ibfk_2'), 'custom_chatbots', 'services', ['service_id'], ['id'])
    op.drop_column('custom_chatbots', 'is_publish')
    op.drop_column('custom_chatbots', 'retrieval_key')
    # ### end Alembic commands ###
