"""uuid introduced

Revision ID: fd7d9a25f32a
Revises: d9c8b26e437e
Create Date: 2026-06-09 06:16:45.440010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid as uuid_lib


# revision identifiers, used by Alembic.
revision: str = 'fd7d9a25f32a'
down_revision: Union[str, Sequence[str], None] = 'd9c8b26e437e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tables = [
        'api_keys', 'custom_chatbots', 'organizations',
        'service_usages', 'services', 'tasks', 'usage_logs', 'users'
    ]

    conn = op.get_bind()

    for table in tables:
        # Check if uuid column already exists
        result = conn.execute(sa.text(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() "
            "AND table_name = :table AND column_name = 'uuid'"
        ), {"table": table})
        exists = result.scalar() > 0

        if not exists:
            op.add_column(table, sa.Column('uuid', sa.String(length=36), nullable=True))

        # Backfill rows that have NULL or empty uuid
        rows = conn.execute(sa.text(
            f"SELECT id FROM {table} WHERE uuid IS NULL OR uuid = ''"
        ))
        for row in rows:
            conn.execute(
                sa.text(f"UPDATE {table} SET uuid = :uuid WHERE id = :id"),
                {"uuid": str(uuid_lib.uuid4()), "id": row[0]}
            )

        # Make non-nullable if not already
        op.alter_column(table, 'uuid',
                        existing_type=sa.String(length=36),
                        nullable=False)

        # Add unique constraint if not already present
        constraint_exists = conn.execute(sa.text(
            "SELECT COUNT(*) FROM information_schema.table_constraints "
            "WHERE table_schema = DATABASE() "
            "AND table_name = :table AND constraint_type = 'UNIQUE'"
        ), {"table": table}).scalar()

        if not constraint_exists:
            op.create_unique_constraint(None, table, ['uuid'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_constraint(None, 'usage_logs', type_='unique')
    op.drop_column('usage_logs', 'uuid')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'uuid')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_column('services', 'uuid')
    op.drop_constraint(None, 'service_usages', type_='unique')
    op.drop_column('service_usages', 'uuid')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'uuid')
    op.drop_constraint(None, 'custom_chatbots', type_='unique')
    op.drop_column('custom_chatbots', 'uuid')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_column('api_keys', 'uuid')
    # ### end Alembic commands ###
